name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/omniscrapper/scheduler/scheduler:latest

      - name: Sign in to Github Registry
        run: docker login docker.pkg.github.com --username Mehonoshin -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker image
        run: docker push docker.pkg.github.com/omniscrapper/scheduler/scheduler:latest
